name: ci
on:
  push:
    #branches:
    #  - 'main'
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Docker meta
        uses: docker/metadata-action@v4
        with:
          images: namickey/spring-boot2-try
          tags: |
            type=semver,pattern={{version}}
      -
        name: echo tag
        run: |
          echo ${{ steps.meta.outputs.tags }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          : # mvn spring-boot:build-image -Dspring-boot.build-image.imageName=namickey/spring-boot2-try:latest
          mvn spring-boot:build-image -Dspring-boot.build-image.imageName=namickey/spring-boot2-try:${{ steps.meta.outputs.tags }}
          docker images
          : # docker push namickey/spring-boot2-try:latest
          docker push namickey/spring-boot2-try:${{ steps.meta.outputs.tags }}